Update android-build.yml

diff --git a/.github/workflows/android-build.yml b/.github/workflows/android-build.yml
--- a/.github/workflows/android-build.yml
+++ b/.github/workflows/android-build.yml
@@ -33,8 +33,17 @@ jobs:
       - name: Build Debug APK
         run: ./gradlew assembleDebug
 
-      - name: List APK files
-        run: ls -l app/build/outputs/apk/debug/
+      - name: Check APK existence
+        run: |
+         if [ -f app/build/outputs/apk/debug/app-debug.apk ]; then
+         echo "APK found"
+         else
+          echo "APK NOT found!"
+          exit 1
+         fi
+
+      - name: List APK directory
+        run: ls -la app/build/outputs/apk/debug/
 
       - name: Upload APK
         uses: actions/upload-artifact@v2
